from newspaper import Article
import logging

# Suppress the newspaper library's logging output
logging.getLogger("newspaper").setLevel(logging.CRITICAL)

def extract_main_content(url):
    # Fetch the article using the URL
    article = Article(url)
    
    # Download the article content
    article.download()
    
    # Parse the article (This will extract headline, text, etc.)
    article.parse()
    
    # Optionally, you can also download additional metadata (like images, keywords, etc.)
    article.nlp()

    # Extract headline, body text, and summary
    headline = article.title
    body_text = article.text
    summary = article.summary  # This is the summary generated by nlp()

    # # Print the extracted content
    # print(f"Headline: {headline}")
    # print(f"Body Text: {body_text}...")  # Print the first 500 characters of body text
    # print(f"Summary: {summary}")  # Print the summary

    return {
        "headline": headline,
        "body_text": body_text,
        "summary": summary
    }

if __name__ == "__main__":
    # Example URL (Replace with actual URLs from your earlier search)
    url = "https://www.tipranks.com/news/company-announcements/nuvve-holding-engages-advisors-for-digital-asset-growth"
    
    content = extract_main_content(url)
    print(content)
